on: [push]

jobs:
  write-good-job:
    runs-on: ubuntu-latest
    name: Check .md files
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2

      # Installs and uses write-good to check all .md files in root directory.
      - name: write-good CL
        id: CL-writegood
        run: |
          npm install
          npm install write-good
          for file in $(find . -name '*.md'); do
            npx write-good $file
          done

