on: [push]

jobs:
  write-good-job:
    runs-on: ubuntu-latest
    name: Check .md files
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2

      # Installs and uses write-good to check all .md files in root directory.
      - name: write-good CL
        id: CL-writegood
        run: |
          npm install
          npm install write-good
          temp=false
          for file in $(find . -name '*.md' -not -path './node_modules/*'); do
            npx write-good $file 
            temp=true
          done

          if [ temp ] 
          then
            exit 2
          fi
          
        working-directory: ./
        shell: bash {0}

